name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/head/main' && 'prod' || 'dev' }}
    steps:
      - run: echo "El secreto ${{secrets.SECRET}}"
      - run: echo "El variable ${{vars.VAR}}"
